version: '3'
services:
  users-mysql:
    build:
     context: ./dir
     dockerfile: Dockerfile
     #Optional
     args:
       buildno: 1
    ports:
      - "8086:8086"
  db:
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'my-secret-pw'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: